<a href="https://colab.research.google.com/github/datagrad/01_Data_Scientist_30_days/blob/main/CTEs_A_Must_Know_for_Data_Scientists.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CTEs : A Googly for Data Scientists

Welcome back to our SQL series for data scientists!
We've journeyed through SQL basics, advanced techniques, subqueries, and window functions.
Today, let’s explore Common Table Expressions (CTEs)—a feature pivotal for writing clean, readable, and modular SQL queries.
I most often call CTE as a googly in cricket which serves as an unexpected but strategic move to outwit the batsman, same way, a CTE in SQL offers a clever and modular way to simplify complex queries, catching data challenges off guard.


## What You'll Learn
- What Are Common Table Expressions (CTEs)?
- Syntax and Structure of CTEs
- Real-world Examples with Our Cricket Dataset
- Use-Cases in Data Science
- Performance Tips

## Understanding the Dataset
To maintain consistency, we'll continue using our cricket dataset, which contains columns like match_id, season, start_date, venue, batting_team, bowling_team, and striker.

## Section 1: What Are Common Table Expressions (CTEs)?
Common Table Expressions (CTEs) provide a way to simplify complex queries by breaking them down into smaller, named sub-queries that you can reference within your main query. Think of CTEs as temporary result sets that are only visible to the query where they are defined.

### Syntax and Structure
The basic syntax for a CTE is:

```sql
WITH cte_name (column_name1, column_name2, ...)
AS (
    -- Subquery
)
-- Main Query using the CTE
```

## Section 2: Real-world Examples with Our Cricket Dataset

### Example 1: Finding Top Scorers in a Season
Let's find the top 5 scorers in the '2007/08' season using a CTE.

```sql
WITH TopScorers AS (
  SELECT striker, SUM(runs) AS total_runs
  FROM cricket_data
  WHERE season = '2007/08'
  GROUP BY striker
)
SELECT *
FROM TopScorers
ORDER BY total_runs DESC
LIMIT 5;
```

### Example 2: Calculating Average Runs Per Match for Each Player

```sql
WITH PlayerMatchRuns AS (
  SELECT match_id, striker, SUM(runs) AS match_runs
  FROM cricket_data
  GROUP BY match_id, striker
),
PlayerAvgRuns AS (
  SELECT striker, AVG(match_runs) AS avg_runs
  FROM PlayerMatchRuns
  GROUP BY striker
)
SELECT * FROM PlayerAvgRuns
ORDER BY avg_runs DESC;
```

## Section 3: Use-Cases in Data Science

1. **Data Transformation**: CTEs can be effectively used for transforming your data before performing analytics.
2. **Hierarchical Data**: CTEs can be used for querying hierarchical data using recursive CTEs.
3. **Debugging**: They make debugging easier as you can isolate different parts of a complex query.

## Section 4: Performance Tips

1. **Avoid Nesting**: Nested CTEs can result in sub-optimal performance.
2. **Be Mindful of Recursion**: Recursive CTEs can be CPU-intensive.
3. **Indexes**: Make sure the fields you're joining on are indexed.

## Conclusion
Common Table Expressions are a hidden gem in SQL. They not only improve the readability of your SQL queries but also offer a modular approach to query design. Mastering CTEs can make your data manipulation tasks more manageable and efficient, making you a more competent data scientist.

Until next time, keep querying and keep exploring!

---

Feel free to connect on Linkedin.com/in/jhakamal to collaborate on projects!

---

Certainly! Breaking down the topic of CTEs into multiple blogs will allow you to go in-depth on each aspect, providing greater value to your readers. Here are the suggested titles along with the topics to be covered:

### 1. "Introduction to Common Table Expressions: The SQL Googly You Didn't See Coming"

**Topics to Cover:**
- What Are CTEs?
- Basic Syntax
- Simple Examples
- Differences between CTEs and Subqueries

---

### 2. "Mastering the Syntax of SQL CTEs: A Data Scientist’s Handbook"

**Topics to Cover:**
- Detailed Syntax Breakdown
- How to Define Column Names in CTEs
- Using Expressions in CTEs
- Advanced Syntax Features

---

### 3. "Real-World Applications of CTEs in Data Science"

**Topics to Cover:**
- Case Studies or Examples with Real-world Data
- Using CTEs with Aggregation Functions
- Use-Cases in Time-Series Analysis, Data Transformation, and Hierarchical Data

---

### 4. "CTEs and Joins: A Match Made in SQL Heaven"

**Topics to Cover:**
- Using CTEs with INNER JOIN, LEFT JOIN, etc.
- When to Use CTEs vs Joins
- Examples of Complex Queries Simplified by Using Both

---

### 5. "Recursive CTEs: The Power and the Pitfalls"

**Topics to Cover:**
- What Are Recursive CTEs?
- Syntax and Structure for Recursive Queries
- Use-Cases: Hierarchical Data, Paths, etc.
- Debugging Recursive CTEs

---

### 6. "Optimizing CTE Performance: Best Practices for Data Scientists"

**Topics to Cover:**
- Understanding Query Execution Plans with CTEs
- Performance Trade-offs
- Indexing Strategies
- Batch Processing and Limiting Scope

---

### 7. "Debugging and Troubleshooting CTEs in SQL"

**Topics to Cover:**
- Common Errors and How to Resolve Them
- Best Practices for Debugging
- Tools and Techniques for Debugging CTEs

---

### 8. "CTEs: Advanced Tips and Tricks for Power Users"

**Topics to Cover:**
- Lesser-known Features and Capabilities
- Combining CTEs with Window Functions or Subqueries
- Complex Examples and Workarounds

---

### 9. "Conclusion: Mastering CTEs to Become a SQL Pro"

**Topics to Cover:**
- Summary of Key Takeaways
- Real-world Success Stories or Case Studies
- Further Reading and Next Steps

---

Each of these blogs can end with a call-to-action, encouraging readers to experiment with the topics discussed and share their experiences, perhaps even inviting them to suggest new topics for future blogs. This would engage your audience more effectively.

Feel free to modify these titles and topics as per your audience and style. Happy blogging!

# BLOG 1


# Introduction to Common Table Expressions: The SQL Googly You Didn't See Coming

Welcome back to our SQL series for data scientists! After our deep dives into SQL essentials, advanced techniques, subqueries, and window functions, it's time to explore a topic that's often overlooked but incredibly useful: Common Table Expressions, or CTEs. Think of a CTE as a googly in cricket—an unexpected, strategic move that can throw even seasoned data professionals off balance. In this blog, we'll introduce you to CTEs and show you how they can simplify your SQL queries.

## What You'll Learn
- What Are Common Table Expressions (CTEs)?
- Basic Syntax of CTEs
- Simple Examples to Get You Started
- Differences Between CTEs and Subqueries

## What Are CTEs?

Common Table Expressions (CTEs) provide a way to simplify complex SQL queries by breaking them down into smaller, named sub-queries. Unlike subqueries or derived tables, a CTE is a temporary result set that is defined within the execution scope of a single SQL statement. This means that you can reference it like you would a regular table, but only within the specific query where it's defined.


## Basic Syntax of CTEs

The syntax for a CTE is straightforward. You start with the WITH keyword, followed by the CTE name and an optional list of columns. Then comes the AS keyword, followed by the query that fetches or computes the data.

```sql
WITH cte_name (column_name1, column_name2, ...)
AS (
  -- Your SQL query here
)
-- Main SQL query that can reference the CTE
```

## Simple Examples to Get You Started

Let's consider our ongoing cricket dataset, which contains details about matches, players, and scores. Suppose we want to find the top 5 scorers in a particular season. Using a CTE, the query would look something like this:

### Example 1: Finding Top Scorers in a Season

```sql
WITH TopScorers AS (
  SELECT striker, SUM(runs) AS total_runs
  FROM cricket_data
  WHERE season = '2021'
  GROUP BY striker
)
SELECT * FROM TopScorers
ORDER BY total_runs DESC
LIMIT 5;
```
In this example, the CTE TopScorers first calculates the total runs for each striker for the 2021 season. The main query then uses this CTE to select the top 5 scorers.



#### Expected Output

```
 striker      | total_runs
--------------|-----------
 Player A     |  950
 Player B     |  860
 Player C     |  820
 Player D     |  800
 Player E     |  780
```

### Example 2: Differences Between CTEs and Subqueries

While both CTEs and subqueries help in decomposing complex queries, they are not the same. Here are some key differences:

Scope: CTEs are accessible only to the query where they are defined. Subqueries can be reused in multiple places.

Readability: CTEs are generally easier to read and maintain since they allow you to separate parts of a complex query into named sub-queries.

Recursion: CTEs can be recursive; subqueries cannot.

Execution: A CTE is more like a named snapshot, materialized just once and used in the main query, often leading to better performance compared to subqueries which may be evaluated multiple times.

## Conclusion

CTEs are an underutilized yet powerful feature in SQL. This is just the tip of the iceberg; in our future blogs, we'll delve deeper into this topic to explore its full potential.

## Call to Action

Ready to become a SQL wizard? Stay tuned for our next blog, where we'll dive deeper into the advanced use-cases of CTEs. Don't forget to share your thoughts or questions in the comments below. If you've found this blog helpful, share it with your network to help others up their SQL game!

If you're working on something exciting or have further questions about CTEs, feel free to connect with me on [LinkedIn](https://www.linkedin.com/in/jhakamal) to collaborate on projects!